### ISSUE TITLE
Calculating motion velocity, dominant direction of movement and dependence of search chips

### ISSUE THREAD

**Issue by arimue** [nasa-jpl/autoRIFT#49]
Hi all, 

I use autoRIFT for offset tracking across a slow-moving landslide based on optical satellite imagery. In doing so, a few more questions came up that I thought you might be able to help me with: 

**1)** Calculation of final motion velocity: in the provided examples on github I saw that the motion velocity is determined using conversion coefficients from radar range/azimuth displacement to x/y-direction motion velocity calculated using Geogrid (winro2vxname, winro2vyname). At first, I thought that these coefficients would only be useful when working with radar data, but in the given example for optical imagery, conversion coefficients are also applied to Landsat-8 data. Is that to project the offset along the local slope? So far I have simply determined the velocity by taking the magnitude of the displacement vector (sqrt(dx²+dy²)), multiplying it by the resolution of the input image, and dividing by the time difference in days *356.

**2)** Besides calculating the velocity, I have also used the estimated horizontal and vertical offset to compute the direction in which the surface is moving (angle to north). My idea was to compare that to the aspect of a DEM and filter out pixels that do not move in the same direction as the slope is oriented. In this context, I noticed that when correlating Sentinel-2 images, there are characteristic displacement directions that are distinct for different image pairs (i.e. not related to topography). Is this a sign of orthorectification/coregistration problems? 
Here are some examples:
![offset_direction_s2](https://user-images.githubusercontent.com/33640758/149577503-aced58c6-9351-4060-8229-c4ada558e003.png)

When correlating Landsat-8 data for the same region, I get a much more homogeneous direction distribution, however, with prominent peaks at 0, 90, 180 and 270° which I attribute to the underlying DEM:

![offset_direction_l8](https://user-images.githubusercontent.com/33640758/149577492-602b2770-ced4-4593-af1a-ab2eb2a7f96a.png)

**3)** About the dependence of search chips: As I am monitoring rather slow motions (~1m/yr), I am using large chip sizes with small search distances. To ensure that the search chips are independent, I need a pretty coarse grid spacing which results in my landslides only being covered by a handful of pixels. Therefore, to better resolve any moving features, I would like to make the grid spacing smaller, introducing a certain spatial correlation of displacement results and noise. However, since I've read that the NDC filter has been refined to now filter noise even on fine grids - how much more of a problem is the dependence of search chips (except for longer runtime)? I compared offset results obtained with the same chip sizes but different grid spacings. Finer grids show greater offset variation over the area of the landslide. How reliable are these details?
![offsetMagnitude_different_gridSpacings_16_32](https://user-images.githubusercontent.com/33640758/149578636-82446888-c63c-4995-8a90-23e464349c2b.png)

**Comment by alex-s-gardner** [comment]
Hi @arimue let me see if I can understand/help 1-by-1:

1. Conversion coefficients for georeferenced optical imagery are only applied to account for differences in image and desired grid projections. You can test this by setting all of the DEM elevations to zero and seeing no change in autoRIFT output. Slope is not used for optical imagery. 

2. Low signals are best recover by staking multiple offsets. Small geolocation/timing errors in individual images can lead to large bias in Dx and Dy. We account for these using a "stable shift correction". You can do the same by removing the median Dx and Dy value calculated over all areas that you expect to be "stable" in your image-footprint. If the landslide is small relative to the image-pair coverage then I would just subtract the median Dx from the Dx field and the median Dy from the Dy field. This will center all non-landslide areas about zeros. Also all displacement staking should be done on individual Dx and Dy components otherwise you'll have a non Gaussian distribution... the very last step can be to calculate velocity magnitude. Also when working with S2 data we have found it necessary to use the l1c data (before radiance correction: https://roda.sentinel-hub.com/sentinel-s2-l1c/readme.html)  as we have found striping in the L2 data. Not sure about the L8 peaks... that might just be an artifact of being able to resolve along pixel displacement better than other directions.... maybe

3. Your results in Figure 3 look really robust... a testament to the modified NDC filter for overlapping grids. The change in variance with grid spacing is just an artifact of differing chips... with the difference across grids likely below the sensor noise so I would ignore.

**Comment by arimue** [comment]
Thanks for your feedback, @alex-s-gardner - that helped a lot. I will test the L1C data.
